debug: true
server:
  port: 8080
springdoc:
  swagger-ui:
    path: /swagger-ui.html
spring:
  datasource:
#    env_file: ./.env-postgres
    url: jdbc:postgresql://snuffleupagus.db.elephantsql.com:5432/opnfduka
    username: opnfduka
    password: aWd-ILVZ-AXKRqxH-KTqpTenrqALgPXB
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create # none, create ...
  sql:
    init:
      platform: postgresql
      mode: always
    output:
      ansi:
        enabled: always
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR